//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrPlayer.Helpers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VrPlayer.Helpers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-Eyed.
        /// </summary>
        internal static string CrossEyed {
            get {
                return ResourceManager.GetString("CrossEyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Screen.
        /// </summary>
        internal static string DualScreen {
            get {
                return ResourceManager.GetString("DualScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string Mono {
            get {
                return ResourceManager.GetString("Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono (Left).
        /// </summary>
        internal static string MonoLeft {
            get {
                return ResourceManager.GetString("MonoLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono (Right).
        /// </summary>
        internal static string MonoRight {
            get {
                return ResourceManager.GetString("MonoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over/Under.
        /// </summary>
        internal static string OverUnder {
            get {
                return ResourceManager.GetString("OverUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side by side.
        /// </summary>
        internal static string SideBySide {
            get {
                return ResourceManager.GetString("SideBySide", resourceCulture);
            }
        }
    }
}
